version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - npm run lint
      - npm run test:unit
      - npm run test:mutation
      - npm run build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - lib/**/*
    - package.json
    - LICENCE.md
    - README.md
    - buildspec-deploy.yml
