version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - echo "sonar.login=${SQ_LOGIN}" >> sonar-project.properties
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
      - unzip ./sonar-scanner-cli-4.6.0.2311-linux.zip
      - export PATH=$PATH:./sonar-scanner-4.6.0.2311-linux/bin/
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - npm run lint
      - npm run test:unit:coverage
      - npm run test:mutation
      - npm run updateSonarQube
      - npm run build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - lib/**/*
    - package.json
    - LICENCE.md
    - README.md
    - buildspec-deploy.yml
cache: 
  paths:
    - node_modules/**/*